from saldo import *
from aluguel import *
from compra import *
from estoque import *
from cliente import *

print(criaCliente("João Pedro Magalhães")+"\n")
print(criaCliente(1)+"\n")
print(criaCliente("João Pedro Magalhães")+"\n")
print(removeCliente("João Pedro Magalhães")+"\n")
print(removeCliente("Felipe Barcellos")+"\n")
print(verificaCliente("Matheus origami")+"\n")
print(verificaCliente("Felipe Barcellos")+"\n")
print(verificaEstoque()+"\n")
print(removeEstoqueAluguel("Monopoly",1)+"\n")
print(removeEstoqueAluguel("dobble",1)+"\n")
print(removeEstoqueAluguel("War",1)+"\n")
print(removeEstoqueAluguel("Monopoly",0)+"\n")
print(removeEstoqueAluguel(1,1)+"\n")
print(adicionaEstoqueAluguel("Monopoly",1)+"\n")
print(adicionaEstoqueAluguel(1,1)+"\n")
print(adicionaEstoqueAluguel("Monopoly",0)+"\n")
print(adicionaEstoqueTotal("Taco,gato,pizza",1)+"\n")
print(adicionaEstoqueTotal(1,1)+"\n")
print(adicionaEstoqueTotal("Taco,gato,pizza",0)+"\n")
print(buscaNoEstoque("Monopoly")+"\n")
print(buscaNoEstoque("coup")+"\n")
print(buscaNoEstoque(1)+"\n")
print(alugaJogo("Monopoly")+"\n")
print(alugaJogo(2)+"\n")
print(devolveJogo("Monopoly")+"\n")
print(devolveJogo("Detetive")+"\n")
print(devolveJogo(3)+"\n")
print(adicionaSaldo(1)+"\n")
print(adicionaSaldo(-1)+"\n")
print(removeSaldo("1")+"\n")
print(removeSaldo(-1)+"\n")
print(verificaSaldo()+"\n")
##print(compraJogo("Monopoly", "data/tabela_de_valores.json", "data/")+"\n")
##print(compraJogo(!, "data/tabela_de_valores.json", "data/")+"\n")
print(adicionaPreferencia("Monopoly", "data/")+"\n")
print(adicionaPreferencia(5, "data/")+"\n")
print(recebePrecoCompra("Monopoly", "data/")+"\n")
print(recebePrecoCompra(1, "data/")+"\n")
print(recebePrecoCompra("Quest", "data/")+"\n")