from saldo import *
from aluguel import *
from compra import *
from estoque import *
from cliente import *

criaCliente("João Pedro Magalhães")
criaCliente(1)
criaCliente("João Pedro Magalhães")
removeCliente("João Pedro Magalhães")
removeCliente("Felipe Barcellos")
verificaCliente("Matheus origami")
verificaCliente("Felipe Barcellos")
verificaEstoque()
removeEstoqueAluguel("Monopoly",1)
removeEstoqueAluguel("dobble",1)
removeEstoqueAluguel("War",1)
removeEstoqueAluguel("Monopoly",0)
removeEstoqueAluguel(1,1)
adicionaEstoqueAluguel("Monopoly",1)
adicionaEstoqueAluguel(1,1)
adicionaEstoqueAluguel("Monopoly",0)
adicionaEstoqueTotal("Taco,gato,pizza",1)
adicionaEstoqueTotal(1,1)
adicionaEstoqueTotal("Taco,gato,pizza",0)
buscaNoEstoque("Monopoly")
buscaNoEstoque("coup")
buscaNoEstoque(1)
alugaJogo("Monopoly")
alugaJogo(2)
devolveJogo("Monopoly")
devolveJogo("Detetive")
devolveJogo(3)
adicionaSaldo(1)
adicionaSaldo(-1)
removeSaldo("1")
removeSaldo(-1)
verificaSaldo()
##compraJogo("Monopoly", "data/tabela_de_valores.json", "data/")
##compraJogo(!, "data/tabela_de_valores.json", "data/")
adicionaPreferencia("Monopoly", "data/")
adicionaPreferencia(5, "data/")
recebePrecoCompra("Monopoly", "data/")
recebePrecoCompra(1, "data/")
recebePrecoCompra("Quest", "data/")